// Types

const types = {
    SET_SKETCH: 'SET_SKETCH',
    SET_PATTERN: 'SET_PATTERN',
    SET_OLDCOLOR: 'SET_OLDCOLOR',
    SET_COLOR: 'SET_COLOR',
    SET_PROGRESS: 'SET_PROGRESS',
    SET_RESULT: 'SET_RESULT',
    SET_RECOMMEND: 'SET_RECOMMEND',
    SET_TOKEN: 'SET_TOKEN',
    SET_CATEGORY: 'SET_CATEGORY',
    SET_MYIMAGE: 'SET_MYIMAGE',
    SET_CHECKPALETTE: 'SET_CHECKPALETTE',
}

export default types;